ALTER TABLE "Booking" ADD COLUMN "paymentStatus" TEXT NOT NULL DEFAULT 'Unpaid';
ALTER TABLE "Booking" ADD COLUMN "paidAmount" TEXT NOT NULL DEFAULT '₹0';
ALTER TABLE "Episode" ADD COLUMN "publishedDate" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "paidAmount" TEXT NOT NULL DEFAULT '₹0';
